spring.application.name=usuario-app
server.port=8080

#Para correr los test unitarios usar esta url y para hacer mvn clean package
spring.datasource.url=jdbc:oracle:thin:@usuario_high?TNS_ADMIN=//Users/valeriagutierrez/Documents/Wallet_usuario
#Para usar docker debo usar esta conexion
#spring.datasource.url=jdbc:oracle:thin:@usuario_high?TNS_ADMIN=./Wallet_usuario
spring.datasource.username=ADMIN
spring.datasource.password=OracleUser123
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.main.allow-bean-definition-overriding=true

# JPA Configuration
#create para la primera ejecucion, update desde la segunda
#para los test unitarios create o update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true